import fs from 'fs';
import path from 'path';
import { parseSkillFile } from './parser.js';

/**
 * Handles systematic audits of content against BookLib skills.
 */
export class BookLibAuditor {
  constructor() {}

  /**
   * Performs an audit of a file against a specific skill.
   */
  async audit(skillPath, targetFilePath) {
    if (!fs.existsSync(skillPath)) {
      throw new Error(`Skill not found at ${skillPath}`);
    }

    if (!fs.existsSync(targetFilePath)) {
      throw new Error(`Target file not found at ${targetFilePath}`);
    }

    const skillMdPath = fs.statSync(skillPath).isDirectory() 
      ? path.join(skillPath, 'SKILL.md') 
      : skillPath;
    
    const skillContent = fs.readFileSync(skillMdPath, 'utf8');
    const chunks = parseSkillFile(skillContent, skillMdPath);
    
    const targetContent = fs.readFileSync(targetFilePath, 'utf8');
    const targetLines = targetContent.split('\n');
    
    // Support both legacy and universal tags
    const principles = chunks.find(c => c.metadata.type === 'framework' || c.metadata.type === 'core_principles')?.text || 'See metadata';
    const pitfalls = chunks.find(c => c.metadata.type === 'pitfalls' || c.metadata.type === 'anti_patterns')?.text || 'See metadata';

    // 1. Static Analysis (Domain-specific low-hanging fruit)
    const auditJsonPath = path.join(path.dirname(skillMdPath), 'audit.json');
    let staticFindings = '';
    if (fs.existsSync(auditJsonPath)) {
      const { rules } = JSON.parse(fs.readFileSync(auditJsonPath, 'utf8'));
      const findings = [];

      for (const rule of rules) {
        const regex = new RegExp(rule.pattern, 'g');
        targetLines.forEach((line, index) => {
          if (regex.test(line)) {
            findings.push(`- ${rule.severity} **${rule.id}**: ${rule.message} (Line ${index + 1}: \`${line.trim()}\`)`);
          }
        });
      }
      
      if (findings.length > 0) {
        staticFindings = `### 🤖 Automated Detections\n${findings.join('\n')}\n`;
      } else {
        staticFindings = `### 🤖 Automated Detections\n*No common pitfalls detected automatically.*\n`;
      }
    }

    return `
# BookLib Active Audit: ${path.basename(skillPath)}
**Target Content**: \`${targetFilePath}\`

## 🛠 Instructions for the Agent
You are tasked with a systematic audit of the provided content against expert frameworks. 
Follow these steps:
1. **Analyze**: Read the target content carefully.
2. **Evaluate**: Compare the work against the "Expert Framework" and "Pitfalls to Avoid".
3. **Report**: Document where the content aligns or violates these expert standards.

---

## 📜 Expert Framework
${principles}

## 🚫 Pitfalls to Avoid
${pitfalls}

---

## 🔍 Audit Findings

${staticFindings}

### 🔴 Critical Misalignments (Manual)
*   (List major deviations from the expert framework)

### 🟡 Opportunities for Improvement
*   (List areas where the content can be sharpened)

### 🟢 Strengths
*   (Acknowledge where the content perfectly embodies the principles)

### 🚀 Recommended Refinement
\`\`\`
// Provide a surgical improvement or rewritten section here
\`\`\`

> **Note**: This audit was generated by the BookLib Universal Engine. 
> Always cite the specific expert items in your findings.
`;
  }
}
